service: serverless-offline-sqs-tutorial

provider:
  name: aws
  runtime: nodejs14.x
  stage: local
  region: eu-west-2

package:
  individually: true
  exclude:
  - functions/**
  - stage_variables/**

plugins:
  - serverless-offline-sqs
  - serverless-offline

custom:
  stage: local
  serverless-offline-sqs:    
    autoCreate: true                 # create queue if not exists
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:9324
    region: eu-west-2
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false

functions:
  message_producer:
    handler: lambda/handler_producer.producer
    description: test.
    events:
      - http:
          path: api/cat_facts   
          method: post
          cors: true

  message_consumer:
    handler: lambda/handler_consumer.consumer
    events:
      - sqs: arn:aws:sqs:region:XXXXXX:cat_facts

resources:
  Resources:
    cat_facts:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: cat_facts
